# -*- coding: utf-8 -*-
"""ZomatoData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdXkqyANtMmfDFYfoxNYPRsQTBeURpGF
"""

# Mount Google Drive to access files
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Import pandas and install pandasql
import pandas as pd
!pip install pandasql

# Load the zomato dataset and display its information
df = pd.read_csv('/content/drive/MyDrive/ZomData/zomato.csv')
df.info()

# Drop irrelevant columns
df2=df.drop(columns=['url','phone','rest_type','dish_liked','reviews_list','menu_item','listed_in(city)'],axis=1)

# Display information about the DataFrame after dropping columns
df2.info()

# Rename columns for clarity
df2.rename({'listed_in(type)':'Restaurant_Type','rate':'Rating','approx_cost(for two people)':'Two_people_cost'},axis=1,inplace=True)
df2.info()

# Check for null values in each column
print(df2.isnull().sum())

# Remove leading/trailing whitespace from the 'Rating' column
df2['Rating'] = df2['Rating'].str.strip()

# Remove '/5' from the 'Rating' column
df2['Rating'] = df2['Rating'].str.replace('/5', '', regex=False)

# Convert the 'Rating' column to numeric, coercing errors
df2['Rating'] = pd.to_numeric(df2['Rating'], errors='coerce')

# Remove currency symbol and commas from 'Two_people_cost'
df2['Two_people_cost'] = df2['Two_people_cost'].str.replace('₹', '', regex=False)
df2['Two_people_cost'] = df2['Two_people_cost'].str.replace(',', '', regex=False)

# Convert 'Two_people_cost' to numeric, coercing errors
df2['Two_people_cost'] = pd.to_numeric(df2['Two_people_cost'], errors='coerce')

# Convert 'online_order' and 'book_table' to boolean
df2['online_order'] = df2['online_order'].str.strip().map({'Yes': True, 'No': False})
df2['book_table'] = df2['book_table'].str.strip().map({'Yes': True, 'No': False})

# Display information about the DataFrame after type conversions
df2.info()

# Fill missing 'Rating' values with the median
df2['Rating'] = df2['Rating'].fillna(df2['Rating'].median())

# Fill missing 'location' values with 'Unknown'
df2['location'] = df2['location'].fillna('Unknown')

# Fill missing 'cuisines' values with 'Various'
df2['cuisines'] = df2['cuisines'].fillna('Various')

# Fill missing 'Two_people_cost' values with the median
df2['Two_people_cost'] = df2['Two_people_cost'].fillna(df2['Two_people_cost'].median())

# Display information about the DataFrame after filling missing values
df2.info()

# Verify that there are no more null values
print(df2.isnull().sum())

# Display the shape of the DataFrame
df2.shape

# Remove duplicate rows
df3=df2.drop_duplicates()

# Display information about the DataFrame after dropping duplicates
df3.info()

# Calculate cost per person by dividing by 2
df3.loc[:, 'Two_people_cost'] = df3['Two_people_cost'] / 2

# Rename the 'Two_people_cost' column to 'cost_per_person'
df3=df3.rename(columns={'Two_people_cost':'cost_per_person'})

# Save the cleaned DataFrame to a CSV file
df3.to_csv("zomato_data_analysis.csv")

# Display information about the final DataFrame
df3.info()

# Apply title casing to key categorical text columns
df3['name'] = df3['name'].str.title()
df3['location'] = df3['location'].str.title()
df3['cuisines'] = df3['cuisines'].str.title()
df3['Restaurant_Type'] = df3['Restaurant_Type'].str.title()

# Display the head of selected columns after title casing
df3[['name', 'location', 'cuisines', 'Restaurant_Type', 'online_order', 'book_table']].head()

# Display the first 10 values of the 'Rating' column
df3['Rating'].head(10)

# Save the cleaned DataFrame to Google Drive
df3.to_csv('/content/drive/MyDrive/zomato_cleaned_data.csv', index=False)

# Convert column names to lowercase and display info
df3.columns = df3.columns.str.lower()
df3.info()

# Save the DataFrame with lowercase column names to Google Drive
df3.to_csv('/content/drive/MyDrive/zomato_cleaned_data.csv', index=False)

